-- Your SQL goes here
create table if not exists t_owner_fee_detail
(
    id          bigint generated by default as identity
    constraint t_owner_fee_detail_pk
    primary key,
    stream_id   varchar               not null,
    room_number varchar               not null,
    owner_name  varchar,
    detail_type varchar               not null,
    amount      numeric(10, 2)        not null,
    comment     text,
    create_by   varchar               not null,
    update_by   varchar               not null,
    create_time timestamp             not null,
    update_time timestamp             not null,
    is_delete   boolean default false not null
    );

comment on table t_owner_fee_detail is '用户金额明细';

comment on column t_owner_fee_detail.id is 'id';

comment on column t_owner_fee_detail.room_number is '房间号';

comment on column t_owner_fee_detail.owner_name is '业主姓名';

comment on column t_owner_fee_detail.detail_type is '类型';

comment on column t_owner_fee_detail.amount is '金额';

comment on column t_owner_fee_detail.comment is '备注';

alter table t_owner_fee_detail
    owner to postgres;

create index if not exists t_owner_fee_detail_create_time_index
    on t_owner_fee_detail (create_time desc);

create unique index if not exists t_owner_fee_detail_id_uindex
    on t_owner_fee_detail (id);

create index if not exists t_owner_fee_detail_owner_name_index
    on t_owner_fee_detail (owner_name);

create index if not exists t_owner_fee_detail_room_number_index
    on t_owner_fee_detail (room_number);

create index if not exists t_owner_fee_detail_stream_id_index
    on t_owner_fee_detail (stream_id);

