create table if not exists t_owner_fee_detail_record
(
    id             bigint generated by default as identity
    constraint t_owner_fee_detail_record_pk
    primary key,
    record_id      varchar               not null,
    room_number    varchar               not null,
    count          integer               not null,
    amount_balance numeric(10, 2)        not null,
    comment        text,
    create_by      varchar               not null,
    update_by      varchar               not null,
    create_time    timestamp             not null,
    update_time    timestamp             not null,
    is_delete      boolean default false not null
    );

comment on table t_owner_fee_detail_record is '用于记录流水节点，方便计算结余';

comment on column t_owner_fee_detail_record.record_id is '记录id';

comment on column t_owner_fee_detail_record.count is '当达到一定数量后会生成新的record';

comment on column t_owner_fee_detail_record.amount_balance is '结余';

alter table t_owner_fee_detail_record
    owner to postgres;

create index if not exists t_owner_fee_detail_record_create_time_index
    on t_owner_fee_detail_record (create_time desc);

create index if not exists t_owner_fee_detail_record_id_index
    on t_owner_fee_detail_record (id);

create index if not exists t_owner_fee_detail_record_record_id_index
    on t_owner_fee_detail_record (record_id desc);

create index if not exists t_owner_fee_detail_record_room_number_index
    on t_owner_fee_detail_record (room_number);

create index if not exists t_owner_fee_detail_record_update_time_index
    on t_owner_fee_detail_record (update_time);

