# For documentation on how to configure this picture_extract,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "repository/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
schema = "public"

[migrations_directory]
dir = "repository/migrations"
