create table if not exists t_approve
(
    id            bigint generated by default as identity
    constraint t_approve_pk
    primary key,
    order_no      varchar               not null,
    approve_state basic.approve_state   not null,
    approve_type  basic.approve_type    not null,
    approve_data  json                  not null,
    comment       text,
    create_by     varchar               not null,
    update_by     varchar               not null,
    create_time   timestamp             not null,
    update_time   timestamp             not null,
    is_delete     boolean default false not null,
    account_id    varchar               not null
);

comment on table t_approve is '审批相关';

comment on column t_approve.order_no is '审批单号';

alter table t_approve
    owner to postgres;

create index if not exists t_approve_create_time_index
    on t_approve (create_time);

create index if not exists t_approve_id_index
    on t_approve (id);

create index if not exists t_approve_order_no_index
    on t_approve (order_no);

create index if not exists t_approve_account_id_index
    on t_approve (account_id);

