create table if not exists t_user
(
    id                  bigint generated by default as identity
    constraint t_user_pk
    primary key,
    account_id          varchar         not null,
    account             varchar         not null,
    password            varchar         not null,
    name                varchar         not null,
    role                basic.role_type not null,
    create_by           varchar         not null,
    update_by           varchar         not null,
    create_time         timestamp       not null,
    update_time         timestamp       not null,
    comment             text,
    is_delete           boolean         not null
);

alter table t_user
    owner to postgres;

create index if not exists t_user_account_id_index
    on t_user (account_id);

create index if not exists t_user_account_index
    on t_user (account);

create index if not exists t_user_id_index
    on t_user (id);

