-- Your SQL goes here
create table if not exists t_user_fast_login
(
    id          bigint generated by default as identity
    constraint t_user_fast_login_pk
    primary key,
    account_id  varchar                             not null,
    create_time timestamp default CURRENT_TIMESTAMP not null
);

comment on table t_user_fast_login is '快速登录工具表';

alter table t_user_fast_login
    owner to postgres;

create index if not exists t_user_fast_login_account_id_index
    on t_user_fast_login (account_id);

create index if not exists t_user_fast_login_id_index
    on t_user_fast_login (id);

