[package]
name = "service"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
management_macro = { path = "../management_macro" }
repository = { path = "../repository" }
diesel.workspace = true
log.workspace = true
chrono.workspace = true
bigdecimal.workspace = true
pg_bigdecimal.workspace = true
serde.workspace = true
serde_json.workspace = true

itertools.workspace = true
rayon.workspace = true