create table if not exists t_tool_table
(
    id             integer generated by default as identity
    constraint t_tool_table_pk
    primary key,
    code           varchar                   not null,
    value          varchar                   not null,
    comment        varchar                   not null,
    "current_date" date default CURRENT_DATE not null
);

comment on table t_tool_table is '工具表';

alter table t_tool_table
    owner to postgres;

