create table if not exists t_price_basic
(
    id             bigint generated by default as identity
    constraint t_price_kind_pk
    primary key,
    name           varchar,
    basic_number   numeric(10, 2),
    create_by      varchar,
    update_by      varchar,
    create_time    timestamp               not null,
    update_time    timestamp default now() not null,
    is_delete      boolean,
    operation_type calculate_operation,
    comment        text,
    basic_code     varchar
    );

comment on column t_price_basic.name is '种类';

comment on column t_price_basic.basic_number is '基数';

comment on column t_price_basic.comment is '备注';

comment on column t_price_basic.basic_code is '用于标识是哪种基础价格';

alter table t_price_basic
    owner to postgres;

