-- Your SQL goes here
create table if not exists t_price_basic
(
    id             bigint generated by default as identity
        constraint t_price_kind_pk
            primary key,
    name           varchar,
    basic_number   numeric,
    create_by      varchar,
    update_by      varchar,
    create_time    timestamp,
    update_time    timestamp,
    is_delete      boolean,
    operation_type calculate_operation,
    comment        text
);

comment on column t_price_basic.name is '种类';

comment on column t_price_basic.basic_number is '基数';

comment on column t_price_basic.comment is '备注';