-- Your SQL goes here
create table if not exists t_user_relate_room
(
    id                bigint generated by default as identity
    constraint t_user_relate_room_pk
    primary key,
    relate_account_id varchar not null,
    relate_number     varchar not null
);

alter table t_user_relate_room
    owner to postgres;

