create table if not exists t_attachment
(
    id                   bigint generated by default as identity
    constraint t_attachment_pk
    primary key,
    attachment_id        varchar               not null,
    attachment_file_name varchar,
    oss_file_name        varchar,
    comment              text,
    status               attachment_state      not null,
    create_by            varchar               not null,
    update_by            varchar               not null,
    create_time          timestamp             not null,
    update_time          timestamp             not null,
    is_delete            boolean default false not null
);

alter table t_attachment
    owner to postgres;

create index if not exists t_attachment_attachment_id_index
    on t_attachment (attachment_id);

create index if not exists t_attachment_create_time_index
    on t_attachment (create_time);

create index if not exists t_attachment_id_index
    on t_attachment (id);

