-- Your SQL goes here
create table if not exists t_property_fee_detail
(
    id                          integer generated by default as identity
        constraint property_fee_detail_pk
            primary key,
    room_number                 varchar,
    room_owner_name             varchar,
    management_fee              numeric,
    part_fee                    numeric,
    machine_room_renovation_fee numeric,
    electric_fee                numeric,
    electric_share_fee          numeric,
    water_fee                   numeric,
    water_share_fee             numeric,
    liquidate_fee               numeric,
    pre_store_fee                numeric,
    recode_version               varchar,
    create_by                   numeric,
    update_by                   varchar,
    create_time                 timestamp,
    update_time                 timestamp,
    is_delete                   boolean,
    delete_at                   timestamp,
    comment                     text,
    total_fee                   numeric
);

comment on column t_property_fee_detail.room_number is '房间号';

comment on column t_property_fee_detail.room_owner_name is '业主名称';

comment on column t_property_fee_detail.management_fee is '物业费';

comment on column t_property_fee_detail.part_fee is '停车费';

comment on column t_property_fee_detail.machine_room_renovation_fee is '机房改造费';

comment on column t_property_fee_detail.electric_fee is '电费';

comment on column t_property_fee_detail.water_fee is '水费';

comment on column t_property_fee_detail.water_share_fee is '水费分摊';

comment on column t_property_fee_detail.liquidate_fee is '违约金';

comment on column t_property_fee_detail.pre_store_fee is '预存金';

comment on column t_property_fee_detail.recode_version is '记录版本如：20210101，by每月更新';

comment on column t_property_fee_detail.total_fee is '总费用';

alter table t_property_fee_detail
    owner to postgres;

create index property_fee_detail_create_by_index
    on t_property_fee_detail (create_by);

create index property_fee_detail_create_time_index
    on t_property_fee_detail (create_time desc);

create index property_fee_detail_recode_version_index
    on t_property_fee_detail (recode_version);

create index property_fee_detail_room_number_index
    on t_property_fee_detail (room_number);

create index property_fee_detail_room_owner_name_index
    on t_property_fee_detail (room_owner_name);

create index property_fee_detail_update_by_index
    on t_property_fee_detail (update_by);

