-- Your SQL goes here
create table if not exists t_owner_basic_info
(
    id          integer generated by default as identity
        constraint t_owner_basic_info_pk
            primary key,
    room_number varchar               not null,
    owner_name  varchar,
    room_square varchar,
    create_by   varchar,
    update_by   varchar,
    create_time    timestamp not null,
    update_time    timestamp not null,
    is_delete   boolean default false not null,
    comment     text,
    other_basic json
);

comment on table t_owner_basic_info is '业主信息表';

comment on column t_owner_basic_info.room_number is '房间号';

comment on column t_owner_basic_info.owner_name is '业主姓名';

comment on column t_owner_basic_info.room_square is '房间大小平方';

comment on column t_owner_basic_info.comment is '备注';

comment on column t_owner_basic_info.other_basic is '一些其它费用/每月';

alter table t_owner_basic_info
    owner to postgres;

