create table if not exists t_owner_basic_info
(
    id          integer generated by default as identity
    constraint t_owner_basic_info_pk
    primary key,
    room_number varchar                 not null,
    owner_name  varchar,
    room_square numeric(10, 2),
    create_by   varchar,
    update_by   varchar,
    create_time timestamp               not null,
    update_time timestamp default now() not null,
    is_delete   boolean   default false not null,
    comment     text,
    other_basic json,
    delete_at   timestamp
    );

comment on table t_owner_basic_info is '业主信息表';

comment on column t_owner_basic_info.room_number is '房间号';

comment on column t_owner_basic_info.owner_name is '业主姓名';

comment on column t_owner_basic_info.room_square is '房间大小平方';

comment on column t_owner_basic_info.comment is '备注';

comment on column t_owner_basic_info.other_basic is '一些其它费用/每月';

alter table t_owner_basic_info
    owner to postgres;

create index if not exists t_owner_basic_info_owner_name_index
    on t_owner_basic_info (owner_name);

create index if not exists t_owner_basic_info_update_time_index
    on t_owner_basic_info (update_time desc);

create unique index if not exists t_owner_basic_info_room_number_is_delete_delete_at_uindex
    on t_owner_basic_info (room_number, is_delete, delete_at);

