create table if not exists t_property_fee_detail
(
    id                          bigint generated by default as identity
    constraint property_fee_detail_pk
    primary key,
    room_number                 varchar,
    room_owner_name             varchar,
    management_fee              numeric(10, 2),
    part_fee                    numeric(10, 2),
    lift_fee                    numeric(10, 2)
    machine_room_renovation_fee numeric(10, 2),
    electric_fee                numeric(10, 2),
    electric_share_fee          numeric(10, 2),
    water_fee                   numeric(10, 2),
    water_share_fee             numeric(10, 2),
    liquidate_fee               numeric(10, 2),
    pre_store_fee               numeric(10, 2),
    record_version              varchar,
    create_by                   varchar                 not null,
    update_by                   varchar                 not null,
    create_time                 timestamp               not null,
    update_time                 timestamp default now() not null,
    is_delete                   boolean   default false not null,
    delete_at                   timestamp,
    comment                     text,
    total_fee                   numeric(10, 2),
    );

comment on column t_property_fee_detail.room_number is '房间号';

comment on column t_property_fee_detail.room_owner_name is '业主名称';

comment on column t_property_fee_detail.management_fee is '物业费';

comment on column t_property_fee_detail.part_fee is '停车费';

comment on column t_property_fee_detail.machine_room_renovation_fee is '机房改造费';

comment on column t_property_fee_detail.electric_fee is '电费';

comment on column t_property_fee_detail.water_fee is '水费';

comment on column t_property_fee_detail.water_share_fee is '水费分摊';

comment on column t_property_fee_detail.liquidate_fee is '违约金';

comment on column t_property_fee_detail.pre_store_fee is '预存金';

comment on column t_property_fee_detail.record_version is '记录版本如：20210101，by每月更新';

comment on column t_property_fee_detail.total_fee is '总费用';

alter table t_property_fee_detail
    owner to postgres;

create index if not exists property_fee_detail_create_time_index
    on t_property_fee_detail (create_time desc);

create index if not exists property_fee_detail_recode_version_index
    on t_property_fee_detail (record_version);

create index if not exists property_fee_detail_room_owner_name_index
    on t_property_fee_detail (room_owner_name);

create index if not exists property_fee_detail_update_by_index
    on t_property_fee_detail (update_by);

create index if not exists property_fee_detail_create_by_index
    on t_property_fee_detail (create_by);

create unique index if not exists property_fee_detail_room_number_index
    on t_property_fee_detail (room_number, record_version, is_delete, delete_at);

