[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
management_macro = { path = "../management_macro" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
log4rs.workspace = true
quote.workspace = true
syn.workspace = true
config.workspace = true
lazy_static.workspace = true
log.workspace = true
actix-web.workspace = true
derive_more.workspace = true
diesel.workspace = true
pq-sys.workspace = true
validator.workspace = true
bigdecimal.workspace = true
actix-cors.workspace = true
tracing-actix-web.workspace = true
base64.workspace = true
diesel_logger.workspace = true
