# This is a sample configuration picture_extract for the application
web_config:
  port: 9000
  host: "0.0.0.0"
  shutting_down_timeout: 30
  keep_alive: 30

# Database configuration
databases:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  database: "property_management"
  database_url: "postgres://postgres:postgres@localhost:5432/property_management?options=-c%20search_path%3Dbasic"

# 应用配置
app_config:
  json_length: 10000
  number_max: 100000000
  number_min: -100000000
  record_max: 100 #生成多少条流水就创建新的记录
  liquidated_damages_rate: 0.1 #违约金比例
  password_sec_key: "[,85/ASVR\"}UYn~&:fUrg$ei$Y!{u#|X"
  jwt_expire_time: 1296000
  jwt_renew_time: 864000
  jwt_secret: "[r!7!)%@r^eyt9q,gI#*5d=%.cZCcm=)"
  jwt_handler_ignore_path: [ "/user_info/login","/user_info/we_chart_login","/user_info/register" ]

open_ssl:
  private_key: "openssl/localhost.key"
  certificate: "openssl/localhost.crt"

excel_config:
  basic_height: 31.5
  basic_width: 9

# 阿里云OSS配置
aliyun_oss_config:
  oss_host: "property-manager-form.oss-cn-heyuan.aliyuncs.com"
  sts_host: "sts.cn-heyuan.aliyuncs.com"
  region: "oss-cn-heyuan"
  access_key_id: "LTAI5tBGS6Pz2sQX7xrMGFzq"
  access_key_secret: "B5m0aZAJpDEtQKzP3lTTHATeXdNjNd"
  sts_role_arn: "acs:ram::1957570988142134:role/temp-role-backend"
  bucket: "property-manager-form"


attachment_config:
  picture_suffix: [ "jpg", "jpeg", "png", "gif", "bmp" ]
  temp_output_dir: "./temp_output"

picture_config:
  owner_table_horizontal_offset: 25
  owner_table_vertical_offset: 15

we_chart_config:
    app_id: "wx613da588948efef3"
    app_secret: "2b034c3afef9f01ca33c8bd9d10878e9"
    host: "api.weixin.qq.com"