[package]
name = "controller"
version.workspace = true
edition.workspace = true
default-run = "RunApp"


[dependencies]
common = { path = "../common" }
repository = { path = "../repository" }
management_macro = { path = "../management_macro" }
actix-web.workspace = true
log.workspace = true
diesel.workspace = true
chrono.workspace = true
bigdecimal.workspace = true
serde.workspace = true






[[bin]]
name = "RunApp"
path = "src/bin/RunApp.rs"

