create table if not exists t_room_info_detail
(
    id                           bigint generated by default as identity
    constraint t_room_info_detail_pk
    primary key,
    room_number                  varchar,
    water_meter_num_before       bigint,
    water_meter_num              bigint,
    water_meter_sub              bigint,
    electricity_meter_num_before bigint,
    electricity_meter_num        bigint,
    electricity_meter_sub        bigint,
    month_version                varchar,
    comment                      varchar,
    create_by                    varchar,
    update_by                    varchar,
    create_time                  timestamp             not null,
    update_time                  timestamp             not null,
    is_delete                    boolean default false not null
);

comment on table t_room_info_detail is '房间读数';

alter table t_room_info_detail
    owner to postgres;

create index if not exists t_room_info_detail_month_version_index
    on t_room_info_detail (month_version);

create unique index if not exists t_room_info_detail_room_number_month_version_uindex
    on t_room_info_detail (room_number, month_version);

create index if not exists t_room_info_detail_update_time_index
    on t_room_info_detail (update_time desc);

